# Generated by Django 4.2 on 2023-09-23 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoModel',
            fields=[
                ('uid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('desc', models.TextField(max_length=200)),
                ('name', models.CharField(db_index=True, max_length=30, unique=True)),
                ('age', models.IntegerField(default=18)),
            ],
            options={
                'db_table': 'info_table',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PepleModel',
            fields=[
                ('uid', models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=30, unique=True)),
                ('age', models.IntegerField(default=18)),
                ('sex', models.CharField(max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('modifyTime', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(null=True, upload_to='static/uploads')),
                ('type', models.ForeignKey(default='普通用户', on_delete=django.db.models.deletion.CASCADE, to='myApp.usertype')),
            ],
        ),
    ]
