# Generated by Django 4.2 on 2023-09-23 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_peplemodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peplemodel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='peoples', to='myApp.usertype'),
        ),
    ]
