# Generated by Django 4.2 on 2023-09-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_movie_collect'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collect',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
