# Generated by Django 4.2 on 2023-09-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='pwd',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
